apiVersion: v1
kind: Service
metadata:
  name: ave-g-user-api-stable
  namespace: stable
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 19993
  selector:
    app: ave-g-user-api-stable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ave-g-user-api-stable
  namespace: stable
  labels:
    app: ave-g-user-api-stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ave-g-user-api-stable
  template:
    metadata:
      labels:
        app: ave-g-user-api-stable
    spec:
      containers:
      - name: ave-g-user-api-stable
        image: registry.digitalocean.com/asap-registry/ave-g-user-api:stable
        ports:
          - containerPort: 19993
            name: http
        # volumeMounts:
        #   - name: configsstable
        #     mountPath: /usr/src/asap/config
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: DEV
      # volumes:
      #   - name: configsstable
      #     configMap:
      #       name: configsstable
      #       items:
      #         - key: default.json
      #           path: default.json
      #         - key: STABLE.json
      #           path: STABLE.json
      #         - key: DEV.json
      #           path: DEV.json
      #         - key: QA.json
      #           path: QA.json
      #         - key: SANDBOX.json
      #           path: SANDBOX.json
      imagePullSecrets:
        - name: asap-registry
